llm:
  service: "openai"
  model: "gpt-4-32k"
nlp:
  server_url: "http://localhost:5557"
memory:
  message_window: 12
extractors:
  documents:
    embeddings:
      enabled: true
      chunk_size: 1000
      dimensions: 384
      service: "local"
  messages:
    summarizer:
      enabled: true
      entities:
        enabled: true
      embeddings:
        enabled: true
        dimensions: 384
        service: "local"
    entities:
      enabled: true
    intent:
      enabled: true
    embeddings:
      enabled: true
      dimensions: 384
      service: "local"
store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  host: 0.0.0.0
  port: 8000
  web_enabled: true
  max_request_size: 5242880